cities=["Addis Ababa", "Adama","hawassa","Bahir Dar"]
print(cities[0])
print(cities[-1])
print(cities[1:3])
print(len(cities))
price = [250, 100, 500]
price.append(750)
print(price)
price.remove(100)
print(price)
price.sort()
price.insert(1,600)
print(price)
price.sort()
print(price)
price.pop()
print(price)
price.reverse()
print(price)
